service: prisma-aws-lambda-deployment

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: ap-northeast-2
  # vpc:
  #   securityGroupIds:
  #     -  # FILLME
  #   subnetIds:
  #     -  # FILLME
  #     -  # FILLME

layers:
  TopicPrismaAwsNodeModules:
    path: lambda-layers-node_modules
  TopicPrismaAwsLibs:
    path: lambda-layers-libs
  TopicPrismaAwsPrismaClient:
    path: lambda-layers-prisma-client

functions:
  graphql:
    name: ${sls:stage}-graphql-server
    handler: graphql/handler.default
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
  plugins:
    - serverless-dotenv-plugin
  layers:
    - { Ref: TopicPrismaAwsNodeModulesLambdaLayer }
    - { Ref: TopicPrismaAwsLibsLambdaLayer }
    - { Ref: TopicPrismaAwsPrismaClientLambdaLayer }
