org: toycrane
service: codepot-backend
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-2
functions:
  graphql:
    name: ${sls:stage}-graphqlServer
    handler: src/index.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
  express:
    name: ${sls:stage}-expressServer
    handler: src/expressServer.expressHandler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin
custom:
  webpack:
    includeModules: true
    packager: "yarn"
    packagerOptions:
      scripts: # this is the magic
        - prisma generate
  serverless-offline:
    httpPort: 4000
    noPrependStageInUrl: true
# only include the Prisma binary required on AWS Lambda while packaging
package:
  patterns:
    - "!node_modules/.prisma/client/query-engine-*"
    - "node_modules/.prisma/client/query-engine-rhel-*"
