name: Deploy develop branch

on:
  push:
    branches:
      - develop

jobs:
  deploy-lambda:
    environment: develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        # 앞에 envkey를 반드시 붙여주어야 함
        with:
          envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          envkey_ENV: ${{ secrets.ENV }}
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          envkey_SLS_DEBUG: ${{ secrets.SLS_DEBUG }}
          envkey_SERVER_URL: ${{ secrets.SERVER_URL }}
          envkey_GH_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
          envkey_GH_SECRET: ${{ secrets.GH_SECRET }}
          file_name: .env

      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy --stage=dev
        # serverless에서만 활용하는 환경 변수 추가
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
