name: Deploy development branch

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: | 
              echo "Hello" 
              echo ${{ secrets.SERVER_URL }}
