name: Deploy development branch

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ENV: ${{ secrets.ENV }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SLS_DEBUG: ${{ secrets.SLS_DEBUG }}
          SERVER_URL: ${{ secrets.SERVER_URL }}
          GH_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
          GH_SECRET: ${{ secrets.GH_SECRET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PRISMA_BINARY_TARGET: rhel-openssl-1.0.x
          file_name: .env

      - name: Prepare prisma client
        run: yarn prisma generate

      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy --stage=dev
